### ISSUE TITLE
Set up Prettier

### ISSUE THREAD

**Issue by illright** [atom-community/atom-languageclient#115]
As I've been working with the codebase, I've noticed how most lines are around 100 characters long, which makes the codebase rather difficult to navigate (makes me collapse the Tree View at times just so everything could fit on my screen). That is an issue on its own, but I think we could resolve it and even more by installing Prettier for this project.

A bit of insight in case you're unfamiliar with Prettier: it's a universal code formatter that is opinionated and unconfigurable by design. It helps to keep line lengths at bay as well as resolve endless debates about code formatting. I admit, there are a couple of formatting decisions in Prettier that I dislike, but when installing it for my projects, I've come to realize that this is a sacrifice well worth settling code formatting once and for all.

Not a priority, just as a future consideration. What do you think?

**Comment by aminya** [comment]
There is a prettier config that the organization uses for all of the packages. I will make a PR and will add it here. 

https://github.com/atom-community/atom-ide-template/blob/master/prettier.config.js

**Comment by illright** [comment]
120 characters on the print width though? That's rather extreme. In my projects I've found 100 to be the comfortable deadline for line lengths, but print width is supposed to be a guideline, not a strict deadline, and having that at 120 means the lines will get very long. Could we alter that to 80-90?

**Comment by UziTech** [comment]
I prefer long lines to breaking things up into multiple lines

```js
const someLongString =
  "Some very very very very very very very very very very very long string"
```

That is a lot harder for me to skim and understand what is happening than having it on the same line.

**Comment by aminya** [comment]
120 is a good balance inside Atom. In a normal zoom inside Atom, if you have Minimap, GitHub pane, and TreeView pane open, you can still see 120 characters.

**Comment by illright** [comment]
The problem is, everyone has different screens :) I'm on a 14" laptop, so when I have just the Tree View open, the last column that fits on my screen is 85. That's why, as I was working with the codebase, I felt really lost and had to hide the tree view to just have the editor fullscreen and only then was I able to properly read the code.

I understand what you're saying about function signature verbosity, I did find myself breaking up lines frequently with TypeScript, but I personally think it pays off.

Feels like I am outnumbered here :p. Could we find a compromise?

**Comment by UziTech** [comment]
I don't think one way is **better** than the other so I think we should go for consistency with other repos in the organization.

The only style component I have a strong opinion about is using tabs instead of spaces mainly for file size, and developer accessibility. Why would you demand a specific indent size when you can easily allow every developer to specify their own preferable indent size? (but I digress).

You could turn on line wrapping in Atom.

**Comment by aminya** [comment]
> tabs instead of spaces

Not an issue for JavaScript, but when working with the languages that depend on in the indentation (e.g. CoffeeScript, Python, YAML, Markdown) a consistent number of spaces becomes very important because this can actually break the code. So, that's why we should go with the safer consistent space number to 

When typing you can still use TAB. It is converted by the editor/formatter to space later. So, the developer will not notice any difference.

This is actually one of the reasons that suggesting code edits for the above languages using GitHub may result in [broken code](https://github.com/atom-community/apm/pull/27#issuecomment-689867079)! 


> You could turn on line wrapping in Atom.

Yes, this is the best option for the smaller screens.

**Comment by UziTech** [comment]
> when working with the languages that depend on in the indentation (e.g. CoffeeScript, Python, YAML, Markdown)

Tabs work for most of those languages too. Plus if someone made a language that only allowed tabs for indentation that wouldn't be a good reason to use tabs.

**Comment by aminya** [comment]
I will make a PR once we merge the open PRs. I don't want to make unnecessary conflicts.

https://github.com/atom-community/atom-languageclient/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
